# Header
menu:
	Home: /
	Archives: /archives
	Tags: /tags
	Categories: /categories
	Github:
		url: https://github.com/owlikesj/hexoblog
		icon: github

# Title on top left of menu
menu_title: OwlikBlog

# URL of the Home page image
index_cover: img/home-bg.jpg

# Disqus Comments Shortname
disqus_shortname: owlikesj

# Miscellaneous
google_analytics: UA-103068178-1

# Social Accounts
social_accounts:
	weibo: http://weibo.com/p/1005052903396770
	github: https://github.com/owlikesj