# Header
menu:
	Home: /
	Archives: /archives
	Tags: /tags
	Categories: /categories
	Github:
		url: https://github.com/owlikesj/hexoblog
		icon: github

# Title on top left of menu
menu_title: OwlikBlog